### DISCUSSION TITLE
[Docker]如何在docker部署时设置代理？

### DISCUSSION THREAD

**Discussion by lersh** [GaiZhenbiao/ChuanhuChatGPT#464] [Q&A] [answered]
> 感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
> 请务必先查看 README 中是否已经对您的问题做出了解答。如果没有，请检索issue，查看有没有相同或类似的问题。如果您确信这是一个前人没有遇到的问题，欢迎提交该issue！注意，请编辑issue标题栏“简短的错误描述”部分，也请替换我们的issue模板中的原文。

### 错误描述
我在局域网里设置了一个http代理，不管是在宿主机，还是容器里，用cul -x http://192.168.50.40:10809 https://www.google.com 都能成功获取返回内容，但在页面上设置代理地址为http://192.168.50.40:10809就一直报错

### 复现操作
高级，设置代理地址：http://192.168.50.40:10809  报错

### 错误截图
如果可以，请提供错误的截图，如部署的网页截图与控制台错误报告的截图。

### 终端（控制台）中的错误报告
如果可以，请复制终端中的主要错误报告。

```console
(请使用错误报告替换本行)
```

### 运行环境
**请填写以下列表：**

- OS: [e.g. Linux Ubuntu]
- Docker version:
- Gradio version:
- Python (或Python3) version:

### 其他
补充说明

**Comment by MZhao-ouo** [comment]
请提供部署的主机和访问的主机之间的关系，这个代理只对部署的机器有效。

**Comment by yyihuan** [comment, marked as answer]
需要配置docker容器的env
 ``` 
    - NO_PROXY=localhost
    - HTTP_PROXY=http://你的代理地址
    - HTTPS_PROXY=http://你的代理地址
 ```
注意，第一个NO_PROXY必须配置，应该是gradio的一个bug

下面是我自己的配置文件，不太安全的使用了host模式（因为这台服务器只提供clash和gpt服务）。在这里我的网络是这样的，首先在docker里运行了一个clash，并获取它在虚拟网络内的ip地址。然后gpt服务设置代理到它对应的ip:host
 ```
version: '3'
services:
  chatgpt:
    container_name: chatgpt
    image: tuchuanhuhuhu/chuanhuchatgpt:latest
    volumes:
     - ./ws:/root/ws
    network_mode: host
    hostname: chat
    environment:
    - my_api_key=***********************8
    - NO_PROXY=localhost
    - HTTP_PROXY=http://172.20.0.1:7890
    - HTTPS_PROXY=http://172.20.0.1:7890
    # command: /bin/bash -c "while true;do sleep 3600;done" 
    tty: true
```
