### ISSUE TITLE
希望提供 docker-compose 部署方式

### ISSUE THREAD

**Issue by rockbenben** [GaiZhenbiao/ChuanhuChatGPT#19]
docker-compose 方便提供映射路径，将 API key、System prompt 和保留会话都保留在 NAS 硬盘存储。

另外，dockerhub 提示没有标签，不能直接通过群晖 Docker 下载。

**Comment by hb-0** [comment]
可以自己打包一个，也可以用我打包的：https://hub.docker.com/r/hbcn/chatgpt-py

**Comment by luohe567** [comment]
通过ChatGPT 转换的docker-compose.yml文件
```
version: '3'
services:
  chatgpt:
    image: chuanhuchatgpt:latest
    container_name: chatgpt
    environment:
      - my_api_key=替换成API
    network_mode: host
```
