### ISSUE TITLE
[功能请求]: 有考虑加入socks5的代理支持吗?

### ISSUE THREAD

**Issue by s7word** [GaiZhenbiao/ChuanhuChatGPT#503]
### 相关问题

目前只有http，与https的代理方式

### 可能的解决办法

pip install PySocks
import socks
import socket

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by ZACKLZ** [comment]
求教一下，docker如何添加代理配置

**Comment by s7word** [comment]
我只知道，docker
可以全局代理出去，也不知道，如何指定单个镜像走代理，该项目的Python环境没有socks5的支持，不然镜像内部就可以直接走代理，应该重新引入支持，再次封装就可以了。😊😊😊

小刘忙 ***@***.***> 于2023年4月4日周二 19:12写道：

**Comment by ZACKLZ** [comment]
我一直在等待作者能够支持socks5 TAT

**Comment by weixhishu** [comment]
是不是socket还是http不是看传输数据用的是什么协议么🧐api请求的就是http

**Comment by MZhao-ouo** [comment]
> 我一直在等待作者能够支持socks5 TAT

支持socks5有什么优点吗？一般代理软件都有提供socks/http/https代理的吧

**Comment by ZACKLZ** [comment]
目前发现有支持，只是不在环境配置里，设置后还是没用，放弃了，不用了

**Comment by liyishuai** [comment]
解决方案：https://github.com/go-gost/gost
示例`docker-compose.yml`：
```
version: '3'
services:
  chatgpt:
    container_name: chatgpt
    image: tuchuanhuhuhu/chuanhuchatgpt
    ports:
      - "7860:7860"
    volumes:
      - "~/ChuanhuChatGPT/history:/app/history"
      - "~/ChuanhuChatGPT/config.json:/app/config.json"
  gost:
    container_name: gost
    image: gogost/gost
    expose:
      - 1080
    command:
      - -L
      - http://:1080
      - -F
      - socks5://host.docker.internal:13659
```
对应的`ChuanhuGPT/config.json`片段：
```json
    // 如果使用代理，请取消注释下面的两行，并替换代理URL
    "https_proxy": "http://gost:1080",
    "http_proxy": "http://gost:1080",
```
